### ISSUE TITLE
Error: No provider for: jupyter.services.document-registry.

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab_json#1]
@jasongrout I'm working on a JSON renderer and using [jupyterlab_vega](https://github.com/altair-viz/jupyterlab_vega) and [jupyterlab/jupyterlab_geojson
](https://github.com/jupyterlab/jupyterlab_geojson) as reference implementations. When I test it, jupyterlab fails to load with the following error:

```
Uncaught (in promise) Error: No provider for: jupyter.services.document-registry.
    at JupyterLab.Application.resolveService (http://localhost:8888/lab/main.bundle.js:274:36)
    at Array.map (native)
    at JupyterLab.Application.activatePlugin (http://localhost:8888/lab/main.bundle.js:236:39)
    at Array.map (native)
    at JupyterLab.Application.start (http://localhost:8888/lab/main.bundle.js:322:34)
    at http://localhost:8888/lab:72:7
```

**Comment by jasongrout** [comment]
This often happens when you have two copies of a dependency. This happens when you include a different version of a dependency than JupyterLab does. Basically, your package is importing the wrong version of a token, so the dependency injection container can't find it.

A more helpful dependency container would go through and see if there are any tokens with the same token name, and maybe suggest that this is the problem and that it can be resolved by paying careful attention to the version numbers. Or perhaps the tokens should have the notion of a version number, so they can report that you are requesting version X, but what is registered is version Y. @blink1073, @afshin, @sccolbert: thoughts?

**Comment by gnestor** [comment]
I'm actually encountering this same error when jupyterlab_widgets is enabled. If I understand you correctly, would `npm link`ing my extension to my local jupyterlab installation fix this (because I'm currently running jupyterlab from master and my extension is dependent on `^0.3.0`?

**Comment by jasongrout** [comment]
Update your dependency to the same version you are running.

**Comment by gnestor** [comment]
After updating the jupyterlab dependency and removing the file handler part of my extension (the part that depends on DocumentRegistry), my extension started working with jupyterlab. However, I updated the jupyterlab dependency for jupyterlab_widgets and I'm still getting the same error.

**Comment by jasongrout** [comment]
We updated jupyterlab_widgets in ipywidgets master already.

**Comment by gnestor** [comment]
I can confirm that I now have both the MIME-type renderer (RenderMime) and file-type renderer (DocumentRegistry) working in jupyterlab now 👍

**Comment by gnestor** [comment]
Regarding ipywidgets, I checked out master and did a `git clean -xfd` and reinstalled everything and now I'm seeing:

```
Uncaught Error: Plugin 'jupyter.extensions.widgetManager' is already registered.
    at JupyterLab.Application.registerPlugin (http://localhost:8888/lab/main.bundle.js:187:20)
    at JupyterLab.Application.registerPlugins (http://localhost:8888/lab/main.bundle.js:210:19)
    at http://localhost:8888/lab:75:7
```

**Comment by jasongrout** [comment]
What does `jupyter labextension list` give?

**Comment by gnestor** [comment]
Does this mean I have 2 different copies of jupyterlab_widgets!?

```
Known labextensions:
config dir: /Users/grant/.jupyter/labconfig
    jupyterlab_widgets  enabled 
    - Validating...
      jupyterlab_widgets  OK
config dir: /Users/grant/anaconda/etc/jupyter/labconfig
    jupyterlab_widgets disabled
    - Validating...
      jupyterlab_widgets  OK
    jupyterlab_json  enabled 
    - Validating...
      jupyterlab_json  OK
```

**Comment by jasongrout** [comment]
Yep, that's what I was wondering. Personally, I'd nuke the user copy, and only use `--sys-prefix` with everything.

**Comment by jasongrout** [comment]
Maybe you were installing into sys prefix, but the user copy was the one enabled?

**Comment by gnestor** [comment]
Alright!! I'm all back to normal! Just tested the widgets in jupyterlab and they look great!
